### ISSUE TITLE
expected Scuttlebutt

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-scuttlebutt#2]
This

```
/Users/julian/git/****/node_modules/level-scuttlebutt/lib/buffered-opener.js:29
      throw new Error('expected Scuttlebutt')
```

can be reproduced by this:

``` js
var levelup = require('levelup');
var levelScuttlebutt = require('level-scuttlebutt');
var Model = require('scuttlebutt/model');
var udid = require('udid');

var db = levelup(__dirname + '/db');
levelScuttlebutt(db, udid, function (name) {
  return new Model();
});
db.scuttlebutt.open('some-name', function (err, model) {});
```

Has the API changed?

**Comment by dominictarr** [comment]
will work if you wait until the db has opened before opening scuttlebutt.
I may change it so it buffers, but I'll have to read through all the leveldb buffering code.

**Comment by juliangruber** [comment]
doesn't levelup already buffer all calls?

**Comment by juliangruber** [comment]
You mean like:

``` js
var levelup = require('levelup');
var levelScuttlebutt = require('level-scuttlebutt');
var Model = require('scuttlebutt/model');
var udid = require('udid');

levelup(__dirname + '/db', function (err, db) {
  if (err) throw err;
  levelScuttlebutt(db, udid, function (name) {
      return new Model();
  }); 
  db.scuttlebutt.open('some-name', function (err, model) {});
});
```

...? That still throws:

```
/Users/julian/git/***/node_modules/level-scuttlebutt/lib/buffered-opener.js:29
      throw new Error('expected Scuttlebutt')
            ^
Error: expected Scuttlebutt
    at /Users/julian/git/***/node_modules/level-scuttlebutt/lib/buffered-opener.js:29:13
    at Function.cached [as open] (/Users/julian/git/***/node_modules/level-scuttlebutt/lib/cache.js:57:5)
    at /Users/julian/git/***/index.js:95:18
    at LevelUP.open (/Users/julian/git/***/node_modules/levelup/lib/levelup.js:114:17)
```

**Comment by juliangruber** [comment]
Btw the map-reduce test fails on my machine. Also I saw that your tests use the

``` js
var db = levelup(path)
```

pattern too?

**Comment by dominictarr** [comment]
I removed that because I thought it was breaking other stuff. I'll look into this soon. I'll move reverting this to the top of my list.

**Comment by dominictarr** [comment]
Hey, I added a test for this, but your code isn't breaking.
tests pass for me, are you at the latest master?

**Comment by juliangruber** [comment]
I just updated and reinstalled all dependencies. I still get this output:

```
 ∴  level-scuttlebutt (master) : npm test

> level-scuttlebutt@4.2.3 test /Users/julian/git/level-scuttlebutt
> set -e; for t in test/*.js; do node $t; done

TAP version 13
# test
ok 1 should be equivalent

1..1
# tests 1
# pass  1

# ok
TAP version 13
# scuttlebutt: map-reduce
open
open
open
open
open
map test-a
map test-b
map test-c
map test-d
map test-e
r [ [ 'square' ], 30 ]
r [ [ 'cube' ], 100 ]
map test-a
map test-b
map test-c
map test-d
map test-e

timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
Error: "end() already called on iterator"
    at ReadStream._cleanup (/Users/julian/git/level-scuttlebutt/node_modules/levelup/lib/read-stream.js:144:20)
    at ReadStream.destroy (/Users/julian/git/level-scuttlebutt/node_modules/levelup/lib/read-stream.js:80:8)
    at Model.module.exports.opener.open.value (/Users/julian/git/level-scuttlebutt/lib/db-opener.js:65:14)
    at Model.g (events.js:192:14)
    at Model.EventEmitter.emit (events.js:126:20)
    at Model.sb.dispose (/Users/julian/git/level-scuttlebutt/node_modules/scuttlebutt/index.js:237:8)
    at Object._onTimeout (/Users/julian/git/level-scuttlebutt/lib/cache.js:88:25)
    at Timer.list.ontimeout (timers.js:101:19)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

**Comment by juliangruber** [comment]
Maybe its a race condition?

**Comment by juliangruber** [comment]
We should have something like browserling for this, or a travis-ci with different operating systems and simulated hardware

**Comment by dominictarr** [comment]
cool, reproduced!

Okay, it's now hanging on the map-reduce test, but the others are passing.

was there something about levelup taking too long to compile to work with travis-ci ? I think @rvagg mentioned something about that?

**Comment by rvagg** [comment]
I vaguely remember something about things taking too long and Travis timing out but if that was a problem it hasn't been for a long time now. Travis is happy with LevelUP and hasn't complained. 
Is this using LevelUP 0.6? If so then a double `end()` called on an iterator might be a new LevelUP bug. It shouldn't be possible, the `ReadStream` should know not to do that regardless what it's told to do by client code.

**Comment by juliangruber** [comment]
My installed version of levelup is 0.5.4

**Comment by rvagg** [comment]
ok, I think that we fixed some issues in this area in that version but shifting to 0.6 wouldn't hurt

**Comment by juliangruber** [comment]
I just updated to 0.6.0 and it still fails with the same error :hamster:

**Comment by rvagg** [comment]
same issue? https://github.com/dominictarr/level-map/issues/1

**Comment by rvagg** [comment]
levelup@0.6.1 ought to fix this.

**Comment by juliangruber** [comment]
sweet, I don't get an error any more! Now the map-reduce test never finishes :O t.end() is called but it still continues mapping and reducing

**Comment by dominictarr** [comment]
hmm, well I update levelup in `level-map` and `level-reduce`, and it doesn't spin around reducing and reducing.
It's just `level-scuttlebutt`.

I'm planning a refactor that will simplify the interaction between level-scuttlebutt and map-reduce,
that will make all this much simpler.
